import 'news_item.dart';

class MockData {
  static List<NewsItem> get getBreakingNews => [
        NewsItem(
          id: '1',
          title: 'Candidate Biden Called Saudi Arabia a \'Pariah.\'',
          description: 'Former Vice President Biden vowed to make Saudi Arabia a pariah for the murder of journalist Jamal Khashoggi.',
          content: 'Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose. Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose. Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose. Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose.',
          imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80',
          author: 'David E Sangar',
          source: 'Live News',
          publishedAt: '4 hours ago',
          category: 'Politics',
          readTime: '2 h',
          views: 376,
        ),
        NewsItem(
          id: '2',
          title: 'V.I.P. Immunization for the Powerful and Their Cronies',
          description: 'A new study shows the powerful get access to vaccines first.',
          content: 'Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose.',
          imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&q=80',
          author: 'Sarah Blake',
          source: 'CNN',
          publishedAt: '4 hours ago',
          category: 'Health',
          readTime: '3 h',
          views: 512,
        ),
        NewsItem(
          id: '3',
          title: 'Tech Giants Face New Antitrust Regulations Globally',
          description: 'Governments worldwide are cracking down on big tech monopolies.',
          content: 'Technology companies are facing unprecedented regulatory scrutiny as governments around the world introduce new antitrust legislation targeting market dominance.',
          imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
          author: 'Mike Johnson',
          source: 'Reuters',
          publishedAt: '6 hours ago',
          category: 'Technology',
          readTime: '4 min',
          views: 890,
        ),
      ];

  static List<NewsItem> get getNewsOfTheDay => [
        NewsItem(
          id: '4',
          title: '\'V.I.P. Immunization\' for the Powerful and Their Cronies Rattles South America',
          description: 'A new study indicates that the condition might be less of a worry than once believed.',
          content: 'Capture the beauty that catches your eye. Capture the beauty that catches your eye with a mirrorless camera that you don\'t want to lose.',
          imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80',
          author: 'CNN',
          source: 'World',
          publishedAt: '2 hours ago',
          category: 'Finance',
          readTime: '4 min',
          views: 1024,
        ),
      ];

  static List<NewsItem> get getDiscoverNews => [
    NewsItem(
      id: '5',
      title: 'Candidate Biden Called Saudi Arabia a \'Pariah.\'',
      description: '',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&q=80',
      author: 'David E Sangar',
      source: 'BBC',
      publishedAt: '4 hours ago',
      category: 'Politics',
    ),
    NewsItem(
      id: '6',
      title: 'Climate Summit Reaches Historic Agreement on Emissions',
      description: '',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&q=80',
      author: 'Emma Wilson',
      source: 'Guardian',
      publishedAt: '5 hours ago',
      category: 'Environment',
    ),
    NewsItem(
      id: '7',
      title: 'Stock Markets Rally as Inflation Data Improves',
      description: '',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80',
      author: 'John Doe',
      source: 'Bloomberg',
      publishedAt: '7 hours ago',
      category: 'Finance',
    ),
    NewsItem(
      id: '8',
      title: 'New Study Links Mediterranean Diet to Longer Life',
      description: '',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
      author: 'Dr. Amy Chen',
      source: 'Health Today',
      publishedAt: '8 hours ago',
      category: 'Health',
    ),
    NewsItem(
      id: '9',
      title: 'SpaceX Successfully Launches New Starship Prototype',
      description: '',
      content: '',
      imageUrl: 'https://images.unsplash.com/photo-1457364887197-9150188c107b?w=400&q=80',
      author: 'NASA Watch',
      source: 'Space.com',
      publishedAt: '10 hours ago',
      category: 'Science',
    ),
  ];
}
