// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJ47r0iWrHlKeXZ-nEYTyaq7mYnRT_jk',
    appId: '1:276518156142:web:5262e433928c128685f37f',
    messagingSenderId: '276518156142',
    projectId: 'news-app-eb6d5',
    authDomain: 'news-app-eb6d5.firebaseapp.com',
    storageBucket: 'news-app-eb6d5.firebasestorage.app',
    measurementId: 'G-JGNHPFXK1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76kcPadfPHwQewF_JdvxzK7fG0i8mXwE',
    appId: '1:276518156142:android:21c60b1bb3614f0485f37f',
    messagingSenderId: '276518156142',
    projectId: 'news-app-eb6d5',
    storageBucket: 'news-app-eb6d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqaUAe8NNuOv4H7L9SQed1Dym20OYpFE',
    appId: '1:276518156142:ios:710e48745673561985f37f',
    messagingSenderId: '276518156142',
    projectId: 'news-app-eb6d5',
    storageBucket: 'news-app-eb6d5.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaqaUAe8NNuOv4H7L9SQed1Dym20OYpFE',
    appId: '1:276518156142:ios:710e48745673561985f37f',
    messagingSenderId: '276518156142',
    projectId: 'news-app-eb6d5',
    storageBucket: 'news-app-eb6d5.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJ47r0iWrHlKeXZ-nEYTyaq7mYnRT_jk',
    appId: '1:276518156142:web:0212a6e2f488a72185f37f',
    messagingSenderId: '276518156142',
    projectId: 'news-app-eb6d5',
    authDomain: 'news-app-eb6d5.firebaseapp.com',
    storageBucket: 'news-app-eb6d5.firebasestorage.app',
    measurementId: 'G-WVWM55CYEN',
  );
}
